# This is a basic workflow to help you get started with Actions

name: Python Unit-Testing (pytest)


on:
  workflow_dispatch:

  push:
    branches:
    - feature/*


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Running Unit-Tests (pytest)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest
          python -m pytest
