# This is a basic workflow to help you get started with Actions

name: Python Test Coverage


on:
  workflow_dispatch:

  pull_request:
    branches: ["master"]

  push:
    branches:
    - feature/*


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Installing Packages
        run: |
          python -m pip install --no-input --upgrade pip
          python -m pip install --no-input --requirement requirements/coverage.txt

      - name: Unit Test Coverage
        run: |
          python -m coverage run --rcfile .github/workflows/coveragerc
          python -m coverage report --rcfile .github/workflows/coveragerc
