# This is a basic workflow to help you get started with Actions

name: Python Test Coverage


on:
  workflow_dispatch:

  push:
    branches:
    - feature/*


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Packages
        run: |
          python -m pip install --no-input --upgrade pip
          python -m pip install --no-input --requirement requirements.txt
          python -m pip install --no-input pytest coverage

      - name: Unit Test Coverage
        run: |
          python -m coverage run --rcfile .github/workflows/coveragerc
          python -m coverage report --rcfile .github/workflows/coveragerc
